name: Create workflow file for C# project
on: push

jobs:
    build:
        runs-on: ubuntu-latest
        name: Run SAST scan on source code
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v2
      
          - name: Setup .NET Core
            uses: actions/setup-dotnet@v5
            with:
              dotnet-version: '5.0'  # You can change this to your desired .NET version
      
          - name: Build and Test
            run: |
              dotnet restore
              dotnet build --configuration Release
              dotnet test
      
          - name: SonarCloud Scan
            uses: sonarsource/sonarcloud-github-action@v1
            env:
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
          - name: Quality Gate Check
            run: |
              if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
                sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.qualitygate.wait=true
              fi



    security:
        runs-on: ubuntu-latest
        needs: build
        name: Run SCA scan using snyk
        steps:
          - uses: actions/checkout@master
          - name: RunSnyk to check for vulnerabilities
            uses: synk/actions/dotnet@master
            continue-on-error: true
            env:
                SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    zap-scan:
        runs-on: ubuntu-latest
        needs: security
        name: Run DAST scan on web application
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
                ref: master
          - name: ZAP Scan
            uses: zaproxy/action-baseline@v0.6.1
            with:
                docker_name: 'owasp/zap2docker-stable'
                target: 'http://testphp.vulnweb.com/'
                rules_file_name: '.zap/rules.tsv'
                cmd_options: '-a'



